version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: hackathon-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    restart: unless-stopped
    networks:
      - hackathon-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: hackathon-frontend
    ports:
      - "19000:19000"  # Expo Metro bundler
      - "19001:19001"  # Expo DevTools
      - "19002:19002"  # Expo web
      - "8081:8081"    # Metro bundler alternative
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hackathon-network

networks:
  hackathon-network:
    driver: bridge
