version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: hackathon-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    restart: unless-stopped
    networks:
      - hackathon-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: hackathon-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hackathon-network

networks:
  hackathon-network:
    driver: bridge
